import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import './globals.css'
import { cn } from '@/lib/utils'
import ThemeProvider from '@/components/provider/ThemeProvider'
import ModalProvider from '@/components/provider/ModalProvider'

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Clonecord Chat Application',
  description: 'Generated by create next app',
}

type TRootLayoutProps = {
  children: ReactNode
}

const RootLayout: FC<TRootLayoutProps> = ({ children }) => {
  return (
    <ClerkProvider>
      <html
        lang={'en'}
        suppressHydrationWarning
      >
        <body
          className={cn(
            font.className,
            'bg-white dark:bg-[#313338]'
          )}
        >
          <ThemeProvider
            attribute={'class'}
            defaultTheme={'dark'}
            enableSystem={false}
            storageKey={'c-appchat-theme'}
          >
            <ModalProvider />
            {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}

export default RootLayout