name: Clonecord action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 21
      - name: Install node_modules
        run: yarn
      - name: Build the project
        run: yarn build
      - name: Sets the vercel env
        run: |
          cd build
          mkdir .vercel
          cd .vercel
          touch project.json
          echo '{"orgId":"kz5QwzncukdCAe9U18OEnU8G","projectId":"prj_5g88J7TXjrPbchDW6ztdzpc3oQnR"}' > project.json
      - name: Rewrites config of vercel
        run: |
          cd build
          touch vercel.json
          echo '{"rewrites":[{"source":"/(.*)","destination":"/"}]}' > vercel.json
      - name: Deloying the project
        # env:
        #   VERCEL_ORG_ID: kz5QwzncukdCAe9U18OEnU8G
        #   VERCEL_PROJECT_ID: prj_5g88J7TXjrPbchDW6ztdzpc3oQnR
        run: yarn deploy
      - name: Setup finish
        run: echo 'Built successfully!'