name: Clonecord action
on: [push]
jobs:
  build-app:
    runs-on: ubuntu-latest
    outputs:
      text: ${{ steps.finished.outputs.text }}
    env:
      DEPLOY_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      DEPLOY_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      DEPLOY_PROJ_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      BUILT_DIR: dist
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 21
      - name: Install node_modules
        run: yarn
      - name: Pull Vercel Environment Information
        run: yarn vercel pull --yes --environment=production --token=$DEPLOY_TOKEN
      - name: Build the project
        run: yarn vercel build --prod --yes --token=$DEPLOY_TOKEN
      - name: Rewrites config of vercel
        run: |
          cd $BUILT_DIR
          touch vercel.json
          echo '{"rewrites":[{"source":"/(.*)","destination":"/"}]}' > vercel.json
      - name: Deloying the project
        run: yarn vercel deploy --prebuilt --prod --token=$DEPLOY_TOKEN
      - name: Setup finish
        id: finished
        run: echo "::set-output name=text::built-app"
  test-app:
    needs: build-app
    runs-on: ubuntu-latest
    env:
      BUILT_JOB_OUTPUT: ${{ needs.build-app.outputs.text }}
    steps:
      - run: echo "Testing $BUILT_JOB_OUTPUT"